[project]
name = "tibeb"
version = "0.1.0"

[build]
command = "go build -o tibeb cmd/main.go"
output_dir = "./bin"

[run]
command = "tibeb"
args = ["--v8"]

[watch]
exclude = ["**/vendor/**", "**/.git/**"]

[env]
GO111MODULE = "on"
GOPROXY = "https://proxy.golang.org,direct"
